"""add_laws_and_judgements_tables

Revision ID: b84514e76146
Revises: 3f6be4fc5c83
Create Date: 2025-06-26 16:03:47.295730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84514e76146'
down_revision: Union[str, None] = '3f6be4fc5c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judgements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.Column('court', sa.String(), nullable=True),
    sa.Column('date_of_judgment', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judgements_case_number'), 'judgements', ['case_number'], unique=False)
    op.create_index(op.f('ix_judgements_id'), 'judgements', ['id'], unique=False)
    op.create_index(op.f('ix_judgements_title'), 'judgements', ['title'], unique=False)
    op.create_table('laws',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laws_id'), 'laws', ['id'], unique=False)
    op.create_index(op.f('ix_laws_title'), 'laws', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_laws_title'), table_name='laws')
    op.drop_index(op.f('ix_laws_id'), table_name='laws')
    op.drop_table('laws')
    op.drop_index(op.f('ix_judgements_title'), table_name='judgements')
    op.drop_index(op.f('ix_judgements_id'), table_name='judgements')
    op.drop_index(op.f('ix_judgements_case_number'), table_name='judgements')
    op.drop_table('judgements')
    # ### end Alembic commands ###
