"""updated_laws_and_judgements_tables

Revision ID: ddfc703cf39b
Revises: b84514e76146
Create Date: 2025-06-26 16:44:50.067030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddfc703cf39b'
down_revision: Union[str, None] = 'b84514e76146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_judgements_case_number', table_name='judgements')
    op.drop_index('ix_judgements_title', table_name='judgements')
    op.drop_column('judgements', 'case_number')
    op.drop_column('judgements', 'court')
    op.drop_column('judgements', 'updated_at')
    op.drop_column('judgements', 'date_of_judgment')
    op.drop_column('judgements', 'created_at')
    op.drop_column('judgements', 'title')
    op.drop_index('ix_laws_title', table_name='laws')
    op.create_index(op.f('ix_laws_summary'), 'laws', ['summary'], unique=False)
    op.drop_column('laws', 'updated_at')
    op.drop_column('laws', 'created_at')
    op.drop_column('laws', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laws', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('laws', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('laws', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_laws_summary'), table_name='laws')
    op.create_index('ix_laws_title', 'laws', ['title'], unique=False)
    op.add_column('judgements', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('judgements', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('judgements', sa.Column('date_of_judgment', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('judgements', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('judgements', sa.Column('court', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('judgements', sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_judgements_title', 'judgements', ['title'], unique=False)
    op.create_index('ix_judgements_case_number', 'judgements', ['case_number'], unique=False)
    # ### end Alembic commands ###
