"""new migration

Revision ID: e942dcb57e94
Revises: f2679a44e960
Create Date: 2025-07-06 10:25:01.207226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e942dcb57e94'
down_revision: Union[str, None] = 'f2679a44e960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgements', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('laws', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laws', 'created_at')
    op.drop_column('judgements', 'created_at')
    # ### end Alembic commands ###
