"""simplify_laws_and_judgements_schema

Revision ID: fdc1e8690e8d
Revises: ddfc703cf39b
Create Date: 2025-06-26 17:05:00.794048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc1e8690e8d'
down_revision: Union[str, None] = 'ddfc703cf39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('judgements', 'metadata_json')
    op.drop_column('laws', 'metadata_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laws', sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('judgements', sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
